//! oh-my-pi adapter (github.com/can1357/oh-my-pi, the `omp` binary).
//!
//! A pi fork that kept pi's v3 session record model, so this adapter is a thin
//! shell over the shared v3 codec in [`super::pi_coding_agent`]: the header's
//! `id` / `timestamp` / `cwd`, `message` rows carrying an `AgentMessage` under
//! `.message`, and the `parentId` -> `id` entry chain are all pi v3 verbatim.
//! What differs is the container, and only in two ways:
//!
//! - **The physical title slot.** Current omp files begin with a fixed-width
//!   256-byte `{"type":"title","v":1,...}` line and put the session header on
//!   the SECOND physical line (`session-title-slot.ts`); legacy files start at
//!   the header. omp's own loader strips the slot and folds it into the logical
//!   header, and so does this adapter - the slot's title / source / updatedAt
//!   land in `options.source.title_slot`, never dropped
//!   (spec.md#adapter-integrity-no-silent-drops) and never a message.
//! - **The sessions directory.** `~/.omp/agent/sessions/<scope>-<basename>-<sha256(cwd)>/`
//!   instead of pi's `--<encoded-cwd>--`. Inert here: the project comes from the
//!   header's `cwd`, and the directory name is kept only as the placement hint
//!   every JSONL adapter records.
//!
//! omp's entry taxonomy is much wider than pi's (`ttsr_injection`,
//! `credential_pin`, `session_init`, `mode_change`, `label`, `title_change`,
//! `reset_boundary`, `custom`, `custom_message`, ...) and needs no per-type work:
//! the shared v3 mapper turns any unrecognized record into a System carrier with
//! its raw record preserved.
//!
//! Two fidelity notes, both deliberate:
//!
//! - omp externalizes images to `~/.omp/agent/blobs/<sha256>` and stores
//!   `blob:sha256:<hash>` refs inline. pond ingests the ref, not the bytes - the
//!   transcript stays faithful to the file, and search never wanted the pixels.
//! - The header's `parentSession` is carried verbatim in `options.source` but
//!   NOT mapped to `parent_session_id`. omp writes either a session id or a
//!   session path there depending on the flow and its own docs call it metadata,
//!   not a typed key, so resolving it is a lineage feature for pi and omp
//!   together (`docs/plans/2608-06-pi-pond-plugin-and-v4-adapters-implementation-plan.md`
//!   section 9 item 2), not a guess this adapter makes per row
//!   (spec.md#model-no-synthesis).
//!
//! Ingest-only by design: see [`OhMyPiFactory::serialize`].
//!
//! Format watch: fixtures are generated by driving omp's OWN session code -
//! `tests/fixtures/adapter/oh-my-pi/generate-fixtures.mjs`, last run against
//! `@oh-my-pi/pi-coding-agent@17.2.15`. A diff against the committed fixtures on
//! a later omp is the signal that this adapter needs the same move.

use std::path::{Path, PathBuf};

use serde::Deserialize;
use serde_json::{Value, json};

use super::{
    Adapter, AdapterError, AdapterFactory, AdapterYieldStream, DiscoverFuture, Env,
    RestoreFidelity, RestoredFile, SkipOracle, SourceWatermark, expand_home,
    jsonl::{
        BoundedRow, JsonlTree, jsonl_tree_discover, jsonl_tree_events, peek_last_line,
        peek_nth_line,
    },
    pi_coding_agent::{SourcePlacement, row_timestamp, v3_events_from_row, v3_session_from_row},
};
use crate::{sessions::IngestEvent, wire::Session};

const NAME: &str = "oh-my-pi";

/// The only session version this adapter decodes. omp is at 3 and migrates
/// older files up on load, so a header naming anything higher is a format move
/// this build predates - a visible, counted skip rather than a half ingest.
const SUPPORTED_SESSION_VERSION: i64 = 3;

/// Stateless factory: opens [`OhMyPiAdapter`] instances and probes for omp's
/// canonical install location under `~/.omp/agent/sessions`.
pub struct OhMyPiFactory;

impl AdapterFactory for OhMyPiFactory {
    fn name(&self) -> &'static str {
        NAME
    }

    fn open(&self, config: Value) -> Result<Box<dyn Adapter>, AdapterError> {
        Ok(Box::new(OhMyPiAdapter::from_config(config)?))
    }

    fn probe_default(&self, env: &Env) -> Option<Value> {
        let path = env.home.join(".omp").join("agent").join("sessions");
        path.exists().then(|| json!({ "path": path }))
    }

    /// Ingest-only: omp restore is not implemented, and a restore pond cannot
    /// verify against a real omp is worse than no restore
    /// (spec.md#adapter-native-restore-lossless - fidelity is reported, never
    /// assumed). The refusal names the working alternative instead of the
    /// symptom, per the CLI error contract: omp loads a slot-less v3 file as a
    /// legacy session, which is exactly what the pi serializer emits.
    fn serialize(
        &self,
        _session: &crate::sessions::SessionWithMessages,
        _fidelity: RestoreFidelity,
    ) -> Result<Vec<RestoredFile>, AdapterError> {
        Err(AdapterError::schema(
            NAME,
            NAME,
            "oh-my-pi captures sessions but cannot restore them yet; \
             `pond resume <id> --to pi-coding-agent --out-dir ~/.omp/agent` writes a v3 \
             transcript omp reads as a legacy session file",
        ))
    }
}

/// `[adapters.oh-my-pi]` config blob: the JSONL sessions root.
#[derive(Debug, Clone, Deserialize)]
struct OhMyPiConfig {
    path: PathBuf,
}

/// Configured omp reader: a tree of `*.jsonl` session files under one sessions
/// root. omp's SQL / Redis `SessionStorage` backends publish through the same
/// local index, so there is no second source to open here.
#[derive(Debug, Clone)]
pub struct OhMyPiAdapter {
    root: PathBuf,
}

impl OhMyPiAdapter {
    pub fn new(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }

    fn from_config(config: Value) -> Result<Self, AdapterError> {
        let cfg: OhMyPiConfig = serde_json::from_value(config)
            .map_err(|err| AdapterError::config(NAME, format!("bad config blob: {err}")))?;
        Ok(Self {
            root: expand_home(cfg.path),
        })
    }
}

impl Adapter for OhMyPiAdapter {
    fn discover(&self) -> DiscoverFuture<'_> {
        jsonl_tree_discover(self)
    }

    fn events_with<'a>(&'a self, oracle: &'a dyn SkipOracle) -> AdapterYieldStream<'a> {
        jsonl_tree_events(self, oracle)
    }

    fn plan<'a>(&'a self, oracle: &'a dyn SkipOracle) -> super::PlanFuture<'a> {
        super::jsonl::jsonl_tree_plan(self, oracle)
    }
}

impl JsonlTree for OhMyPiAdapter {
    type State = ();

    fn name(&self) -> &'static str {
        NAME
    }

    fn root(&self) -> &Path {
        &self.root
    }

    fn peek_session_id(&self, path: &Path, first_line: &str) -> Option<String> {
        let first: Value = serde_json::from_str(first_line).ok()?;
        // The title slot holds no id, so the freshness gate has to look one
        // line further or it would disable itself on every current omp file and
        // re-read the whole corpus each sync. Reading the second line is another
        // bounded peek of the same file, not a parse of it.
        let head = if is_title_slot(&first) {
            peek_nth_line(path, 2).and_then(|line| serde_json::from_str::<Value>(&line).ok())?
        } else {
            first
        };
        is_session_head(&head)
            .then(|| head.get("id").and_then(Value::as_str))
            .flatten()
            .map(ToOwned::to_owned)
    }

    fn peek_watermark(&self, path: &Path) -> SourceWatermark {
        // Append-ordered, so the last line is the latest event. A file holding
        // only its slot and header has no ingestible content yet and reads as
        // `Opaque` (re-read) rather than fresh, and the slot itself is rewritten
        // in place on every rename - its `updatedAt` is not an event time, which
        // is why `row_timestamp` (keyed on `timestamp`) is the right reader.
        let last = || -> Option<i64> {
            let row: Value = serde_json::from_str(&peek_last_line(path)?).ok()?;
            if is_title_slot(&row) || is_session_head(&row) {
                return None;
            }
            row_timestamp(&row).map(|ts| ts.timestamp_micros())
        };
        match last() {
            Some(ts) => SourceWatermark::At(ts),
            None => SourceWatermark::Opaque,
        }
    }

    fn unsupported_reason(&self, path: &Path, rows: &[BoundedRow]) -> Option<String> {
        let head = &logical_head(rows)?.value;
        let version = head.get("version").and_then(Value::as_i64)?;
        (is_session_head(head) && version > SUPPORTED_SESSION_VERSION).then(|| {
            format!(
                "{}: oh-my-pi session version {version} is newer than this pond build \
                 understands (supported: {SUPPORTED_SESSION_VERSION}); upgrade pond",
                path.display(),
            )
        })
    }

    fn session(&self, path: &Path, rows: &[BoundedRow]) -> Result<Session, AdapterError> {
        let path_display = path.display().to_string();
        let head = logical_head(rows).ok_or_else(|| {
            // A slot with no header behind it is a session omp has not
            // materialized yet, not a decodable transcript.
            AdapterError::schema(
                NAME,
                path_display.clone(),
                "session file has a title slot but no session header",
            )
        })?;
        let at_head = format!("{path_display}:{}", head.line);
        if !is_session_head(&head.value) {
            return Err(AdapterError::schema(
                NAME,
                at_head,
                "first record after the optional title slot must be a `session` header",
            ));
        }

        let placement = SourcePlacement {
            project_slug: path
                .parent()
                .and_then(|p| p.file_name())
                .and_then(|n| n.to_str())
                .map(ToOwned::to_owned),
            file_name: path
                .file_name()
                .and_then(|n| n.to_str())
                .map(ToOwned::to_owned),
        };
        let mut session = v3_session_from_row(NAME, &head.value, &at_head, &placement)?;
        fold_title_slot(&mut session, rows.first().map(|row| &row.value));
        Ok(session)
    }

    fn events_from_row(
        &self,
        session: &Session,
        row: &BoundedRow,
        _state: &mut Self::State,
    ) -> Result<Vec<IngestEvent>, String> {
        // The slot is container framing folded into the session, not an entry -
        // but only on the physical first line, which is the sole place omp
        // writes it. A `title`-shaped row anywhere else is not framing, so it
        // rides the carrier path and stays visible
        // (spec.md#adapter-integrity-no-silent-drops).
        if row.line == 1 && is_title_slot(&row.value) {
            return Ok(Vec::new());
        }
        v3_events_from_row(&session.id, row.line, &row.value, session.created_at)
    }
}

/// omp's fixed-width first-line title slot (`session-title-slot.ts`): `type`
/// plus the `v: 1` shape marker, which is what separates it from a real entry.
fn is_title_slot(row: &Value) -> bool {
    row.get("type").and_then(Value::as_str) == Some("title")
        && row.get("v").and_then(Value::as_i64) == Some(1)
}

fn is_session_head(row: &Value) -> bool {
    row.get("type").and_then(Value::as_str) == Some("session")
}

/// The first row that is not the physical title slot - the logical head omp's
/// own loader exposes. One predicate, so the version gate and the session
/// mapper can never disagree about which row is the header.
fn logical_head(rows: &[BoundedRow]) -> Option<&BoundedRow> {
    rows.iter().find(|row| !is_title_slot(&row.value))
}

/// Carry the stripped slot into the session's source options so folding it is
/// lossless. Absent for a legacy slot-less file, which is why this is not an
/// error path.
fn fold_title_slot(session: &mut Session, first: Option<&Value>) {
    let Some(slot) = first.filter(|row| is_title_slot(row)) else {
        return;
    };
    if let Some(source) = session
        .options
        .get_mut("source")
        .and_then(Value::as_object_mut)
    {
        source.insert(
            "title_slot".to_owned(),
            json!({
                "title": slot.get("title"),
                "source": slot.get("source"),
                "updated_at": slot.get("updatedAt"),
            }),
        );
    }
}

#[cfg(test)]
mod tests {
    //! End-to-end tests for the oh-my-pi adapter: ingest the committed fixture
    //! corpus (generated by driving omp's own title-slot serializer, see
    //! `tests/fixtures/adapter/oh-my-pi/generate-fixtures.mjs`) and assert
    //! pond's canonical shape comes out the other side.
    #![allow(clippy::expect_used, clippy::unwrap_used)]

    use super::*;
    use crate::{
        adapter::jsonl::peek_first_line, handlers::ingest_adapter, sessions::Store, wire::Message,
    };
    use tempfile::TempDir;

    // Manifest-dir anchored: unit tests must not depend on the process cwd.
    const FIXTURES: &str = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/adapter/oh-my-pi/sessions"
    );
    const BUCKET: &str = "home-omp-demo-9f2c1ab3c4d5e6f7";
    const MAIN: &str = "0a1b2c3d4e5f6071";
    const FORK: &str = "1b2c3d4e5f607182";
    const LEGACY: &str = "legacy00000001";
    const PROJECT: &str = "/Users/user/Projects/omp-demo";

    fn main_file() -> PathBuf {
        Path::new(FIXTURES)
            .join(BUCKET)
            .join(format!("2026-08-12T10-00-00-000Z_{MAIN}.jsonl"))
    }

    async fn ingest_fixtures(temp: &TempDir) -> anyhow::Result<Store> {
        let store = Store::open_local(temp.path().join("store")).await?;
        let summary = ingest_adapter(
            &store,
            &OhMyPiAdapter::new(FIXTURES),
            &crate::adapter::NoopOracle,
            |_| {},
        )
        .await?;
        anyhow::ensure!(summary.dropped_events == 0, "no event may be dropped");
        anyhow::ensure!(summary.dropped_sessions == 0, "no session may be dropped");
        Ok(store)
    }

    #[test]
    fn probe_default_finds_omp_sessions_under_home() -> anyhow::Result<()> {
        crate::adapter::test_support::assert_probe_default(
            &OhMyPiFactory,
            &[".omp", "agent", "sessions"],
        )
    }

    /// The slot is container framing: folded into the session losslessly, never
    /// a message, and the header behind it still drives every canonical field.
    #[tokio::test(flavor = "multi_thread")]
    async fn the_title_slot_is_folded_into_the_session() -> anyhow::Result<()> {
        let temp = TempDir::new()?;
        let store = ingest_fixtures(&temp).await?;

        let main = store.get_session(MAIN).await?.expect("main session lands");
        assert_eq!(main.session.source_agent, NAME);
        assert_eq!(&*main.session.project, PROJECT);
        let source = main.session.options.get("source").expect("source options");
        assert_eq!(source.get("adapter"), Some(&json!(NAME)));
        assert_eq!(source.get("format"), Some(&json!(3)));
        assert_eq!(
            source.get("title_slot").and_then(|slot| slot.get("title")),
            Some(&json!("harness problem")),
            "the stripped slot survives in options rather than being dropped",
        );
        // The placement hint is omp's hashed bucket, not a pi-style slug.
        assert_eq!(source.get("project_slug"), Some(&json!(BUCKET)));

        assert!(
            !main.messages.iter().any(|message| matches!(
                &message.message,
                Message::System { content, .. } if content.as_deref().map(String::as_str) == Some("title")
            )),
            "the slot must not mint a carrier message",
        );
        Ok(())
    }

    /// A legacy slot-less file is still what omp reads for older sessions, so it
    /// must read through the same path with no slot recorded.
    #[tokio::test(flavor = "multi_thread")]
    async fn a_legacy_slotless_session_ingests() -> anyhow::Result<()> {
        let temp = TempDir::new()?;
        let store = ingest_fixtures(&temp).await?;

        let legacy = store.get_session(LEGACY).await?.expect("legacy session");
        assert_eq!(&*legacy.session.project, PROJECT);
        assert!(
            legacy
                .session
                .options
                .get("source")
                .and_then(|source| source.get("title_slot"))
                .is_none(),
            "no slot in the file means no slot in options",
        );
        assert!(
            legacy
                .messages
                .iter()
                .any(|message| matches!(&message.message, Message::User { .. })),
            "the legacy transcript's user turn still lands",
        );
        Ok(())
    }

    /// omp's wider entry taxonomy rides the shared v3 carrier path: conversation
    /// stays conversation, orchestration stays System, nothing is dropped
    /// (spec.md#model-part-provenance placement rule 3).
    #[tokio::test(flavor = "multi_thread")]
    async fn omp_only_entry_types_become_system_carriers() -> anyhow::Result<()> {
        let temp = TempDir::new()?;
        let store = ingest_fixtures(&temp).await?;
        let main = store.get_session(MAIN).await?.expect("main session lands");

        let carriers: Vec<Option<String>> = main
            .messages
            .iter()
            .filter_map(|message| match &message.message {
                Message::System { content, .. } => {
                    Some(content.as_deref().map(ToString::to_string))
                }
                _ => None,
            })
            .collect();
        assert!(
            carriers.contains(&Some("ttsr_injection".to_owned())),
            "an omp-only entry type must survive as a carrier: {carriers:?}",
        );
        assert!(
            carriers.contains(&Some("model_change".to_owned())),
            "a shared pi carrier still maps: {carriers:?}",
        );

        let count = |kind: &str| {
            main.messages
                .iter()
                .filter(|message| match &message.message {
                    Message::User { .. } => kind == "user",
                    Message::Assistant { .. } => kind == "assistant",
                    Message::Tool { .. } => kind == "tool",
                    Message::System { .. } => kind == "system",
                })
                .count()
        };
        assert_eq!(count("user"), 2);
        assert_eq!(count("assistant"), 1);
        assert_eq!(count("tool"), 1);

        let fork = store.get_session(FORK).await?.expect("fork session lands");
        assert!(
            fork.messages.iter().any(|message| matches!(
                &message.message,
                Message::System { content, .. } if content.as_deref().map(String::as_str) == Some("branch_summary")
            )),
            "omp's branch summary is orchestration, not conversation",
        );
        Ok(())
    }

    /// omp's `parentSession` is opaque (id OR path, by flow), so it is carried
    /// verbatim and never guessed into lineage (spec.md#model-no-synthesis).
    #[tokio::test(flavor = "multi_thread")]
    async fn the_opaque_parent_marker_is_carried_not_interpreted() -> anyhow::Result<()> {
        let temp = TempDir::new()?;
        let store = ingest_fixtures(&temp).await?;

        let fork = store.get_session(FORK).await?.expect("fork session lands");
        assert_eq!(fork.session.parent_session_id, None);
        assert_eq!(
            fork.session
                .options
                .get("source")
                .and_then(|source| source.get("raw_record"))
                .and_then(|raw| raw.get("parentSession")),
            Some(&json!(MAIN)),
        );
        Ok(())
    }

    /// The slot is framing only where omp writes it. A `title`-shaped row deeper
    /// in the file is not framing, so it must stay visible as a carrier instead
    /// of being skipped into nothing.
    #[test]
    fn a_title_shaped_row_off_line_one_stays_visible() {
        let adapter = OhMyPiAdapter::new(FIXTURES);
        let session = Session {
            id: "sess1".to_owned(),
            parent_session_id: None,
            parent_message_id: None,
            source_agent: NAME.to_owned(),
            created_at: chrono::Utc::now(),
            project: crate::adapter::extract::Extracted::from_test_value(PROJECT.to_owned()),
            options: crate::wire::ProviderOptions::new(),
        };
        let slot = json!({"type": "title", "v": 1, "title": "t", "updatedAt": "x", "pad": " "});

        let framing = adapter
            .events_from_row(
                &session,
                &BoundedRow {
                    line: 1,
                    value: slot.clone(),
                },
                &mut (),
            )
            .expect("line 1 is framing");
        assert!(framing.is_empty(), "the physical slot yields no event");

        let deeper = adapter
            .events_from_row(
                &session,
                &BoundedRow {
                    line: 7,
                    value: slot,
                },
                &mut (),
            )
            .expect("a later row still maps");
        assert!(
            deeper
                .iter()
                .any(|event| matches!(event, IngestEvent::Message(Message::System { .. }))),
            "a title-shaped row off line 1 becomes a carrier, never a silent drop",
        );
    }

    /// The freshness gate must see the id behind the slot, or every sync
    /// re-reads the whole omp corpus.
    #[test]
    fn the_freshness_peek_reads_through_the_title_slot() {
        let path = main_file();
        let adapter = OhMyPiAdapter::new(FIXTURES);

        let first = peek_first_line(&path).expect("first line");
        assert_eq!(
            adapter.peek_session_id(&path, &first),
            Some(MAIN.to_owned()),
            "a slot-fronted file still gates on its session id",
        );
        assert!(matches!(
            adapter.peek_watermark(&path),
            SourceWatermark::At(_)
        ));
    }

    /// A file omp created but has not materialized yet (slot only) has no id and
    /// no watermark: `Opaque` re-reads rather than claiming freshness.
    #[test]
    fn a_slot_only_file_is_opaque() -> anyhow::Result<()> {
        let temp = TempDir::new()?;
        let bucket = temp.path().join("sessions").join("home-omp-x-1");
        std::fs::create_dir_all(&bucket)?;
        let path = bucket.join("2026-08-12T11-00-00-000Z_slotonly0000001.jsonl");
        let body = std::fs::read_to_string(main_file())?;
        let slot_line = body.lines().next().expect("slot line");
        std::fs::write(&path, format!("{slot_line}\n"))?;

        let adapter = OhMyPiAdapter::new(temp.path().join("sessions"));
        let first = peek_first_line(&path).expect("first line");
        assert_eq!(adapter.peek_session_id(&path, &first), None);
        assert!(matches!(
            adapter.peek_watermark(&path),
            SourceWatermark::Opaque
        ));
        Ok(())
    }

    /// A newer session version is a visible, counted skip that names the file and
    /// the fix - never a half-understood ingest.
    #[test]
    fn a_newer_session_version_is_a_named_skip() {
        let adapter = OhMyPiAdapter::new(FIXTURES);
        let path = Path::new("/tmp/omp/sessions/bucket/x.jsonl");
        let slot = json!({"type": "title", "v": 1, "title": "t", "updatedAt": "x", "pad": " "});
        let rows = |version: i64| {
            vec![
                BoundedRow {
                    line: 1,
                    value: slot.clone(),
                },
                BoundedRow {
                    line: 2,
                    value: json!({
                        "type": "session", "version": version, "id": "sess1",
                        "timestamp": "2026-08-12T10:00:00.000Z", "cwd": PROJECT,
                    }),
                },
            ]
        };

        let reason = adapter
            .unsupported_reason(path, &rows(4))
            .expect("a newer version is unsupported");
        assert!(reason.contains("version 4"), "{reason}");
        assert!(reason.contains("upgrade pond"), "{reason}");
        assert!(
            adapter.unsupported_reason(path, &rows(3)).is_none(),
            "the supported version reads normally",
        );
    }

    /// Ingest-only: the refusal names the working alternative, per the CLI error
    /// contract.
    #[test]
    fn restore_refuses_and_names_the_alternative() {
        let session = crate::sessions::SessionWithMessages {
            session: Session {
                id: "sess1".to_owned(),
                parent_session_id: None,
                parent_message_id: None,
                source_agent: NAME.to_owned(),
                created_at: chrono::Utc::now(),
                project: crate::adapter::extract::Extracted::from_test_value(PROJECT.to_owned()),
                options: crate::wire::ProviderOptions::new(),
            },
            messages: Vec::new(),
        };

        let error = OhMyPiFactory
            .serialize(&session, RestoreFidelity::Native)
            .expect_err("oh-my-pi is ingest-only");
        let text = error.to_string();
        assert!(text.contains("pi-coding-agent"), "{text}");
        assert!(text.contains("--out-dir ~/.omp/agent"), "{text}");
    }
}
