name: release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release-plz:
    name: release-plz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - uses: actions-rust-lang/setup-rust-toolchain@v1.16.1

      - uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
